# Generated by Django 2.1.5 on 2019-01-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HanreiPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(max_length=30)),
                ('case_number', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('case_name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('x_attorney_name', models.CharField(max_length=30)),
                ('y_attorney_name', models.CharField(max_length=30)),
                ('judge_name', models.CharField(max_length=30)),
                ('result', models.CharField(max_length=30)),
                ('text', models.TextField()),
            ],
        ),
    ]
