# Generated by Django 2.2.1 on 2019-06-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanrei', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HanreiPost',
            new_name='CasePost',
        ),
    ]
