# Generated by Django 2.2.1 on 2019-06-19 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanrei', '0002_auto_20190617_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CasePost',
            new_name='HanreiPost',
        ),
    ]
