# Generated by Django 2.2.1 on 2019-06-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanrei', '0003_auto_20190619_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hanreipost',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hanreipost',
            name='result',
            field=models.CharField(max_length=10),
        ),
    ]
