# Generated by Django 2.2.1 on 2019-06-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanrei', '0004_auto_20190626_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hanreipost',
            name='result',
        ),
        migrations.AddField(
            model_name='hanreipost',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hanreipost',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
