# Generated by Django 2.2.1 on 2019-06-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanrei', '0005_auto_20190626_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanreipost',
            name='judgement',
            field=models.FileField(default=123, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
