# Generated by Django 2.2.1 on 2019-07-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanrei', '0008_auto_20190721_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hanreipost',
            name='date',
            field=models.DateField(),
        ),
    ]
