# Generated by Django 2.2.1 on 2019-10-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanrei', '0010_remove_hanreipost_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shrine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locate', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('text', models.TextField()),
                ('photo', models.FileField(upload_to='uploads/%Y/%m/%d')),
            ],
        ),
    ]
